#define LOGIN_ERROR_BAD_VALUES 1
#define LOGOUT_ERROR_BAD_VALUES 2
#define UNREGISTER_ERROR_BAD_VALUES 3 
#define MY_AUCTIONS_ERROR_BAD_UID 4
#define MY_BIDS_ERROR_BAD_UID 5
#define SHOW_RECORD_ERROR_BAD_AID 6
